In [1]:
import numpy as np 
import pyproffit
import matplotlib.pyplot as plt
import h5py
import astropy.io as fits

from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.wcs import WCS

from astropy.convolution import Gaussian2DKernel
from astropy.modeling.models import Lorentz1D
from astropy.convolution import convolve_fft

%matplotlib inline

In [2]:
h5_file_halo = 'grid_halo_TNG100-1_99_111.hdf5'
fits_file_halo = 'grid_halo_TNG100-1_99_111.fits'

In [3]:
with h5py.File(h5_file_halo, 'r+') as f:
    print("Keys: %s" % f.keys())
    # Get the data
    grid_data = f['grid'][...]
    print(grid_data)
    header_data = f['Header']
    #print(data)

Keys: <KeysViewHDF5 ['Header', 'grid']>
[[99. 99. 99. ... 99. 99. 99.]
 [99. 99. 99. ... 99. 99. 99.]
 [99. 99. 99. ... 99. 99. 99.]
 ...
 [99. 99. 99. ... 99. 99. 99.]
 [99. 99. 99. ... 99. 99. 99.]
 [99. 99. 99. ... 99. 99. 99.]]


In [4]:
with h5py.File(h5_file_halo, 'r') as f:
    data = f['grid'][()]
    hdu = fits.PrimaryHDU(data)
    hdu.writeto(fits_file_halo, overwrite=True)

AttributeError: module 'astropy.io' has no attribute 'PrimaryHDU'

In [ ]:
fits

Type:        module
String form: <module 'astropy.io' from '/opt/homebrew/anaconda3/envs/astro/lib/python3.13/site-packages/astropy/io/__init__.py'>
File:        /opt/homebrew/anaconda3/envs/astro/lib/python3.13/site-packages/astropy/io/__init__.py
Docstring:  
This subpackage contains modules and packages for interpreting data storage
formats used by and in astropy.