In [17]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
from astropy.io import fits   # unambiguous import — avoids astropy.io namespace collision
from astropy.wcs import WCS

%matplotlib inline

In [18]:
h5_file_halo = 'grid_halo_TNG100-1_99_111.hdf5'
fits_file_halo = 'grid_halo_TNG100-1_99_111.fits'

In [19]:
with h5py.File(h5_file_halo, 'r+') as f:
    print("Keys: %s" % f.keys())
    # Get the data
    grid_data = f['grid'][...]
    print(grid_data)
    header_data = f['Header']
    #print(data)

Keys: <KeysViewHDF5 ['Header', 'grid']>
[[99. 99. 99. ... 99. 99. 99.]
 [99. 99. 99. ... 99. 99. 99.]
 [99. 99. 99. ... 99. 99. 99.]
 ...
 [99. 99. 99. ... 99. 99. 99.]
 [99. 99. 99. ... 99. 99. 99.]
 [99. 99. 99. ... 99. 99. 99.]]


In [20]:
with h5py.File(h5_file_halo, 'r') as f:
    data = f['grid'][()]
    h5_hdr = dict(f['Header'].attrs)

# Build FITS header with HDF5 metadata
hdr = fits.Header()
hdr['SIM']     = (h5_hdr['sim_name'], 'IllustrisTNG simulation')
hdr['SNAP']    = (int(h5_hdr['snap']),  'Snapshot number')
hdr['HALO_ID'] = (int(h5_hdr['id']),   'Subhalo/halo ID')
hdr['TYPE']    = (h5_hdr['type'],      'Object type')
hdr['FILL_VAL']= (99.0,               'Sentinel value for empty pixels')
hdr['BUNIT']   = ('log SB',           'Pixel units (log surface brightness)')

hdu = fits.PrimaryHDU(data, header=hdr)
hdu.writeto(fits_file_halo, overwrite=True)
print(f"Written: {fits_file_halo}  shape={data.shape}  dtype={data.dtype}")

Written: grid_halo_TNG100-1_99_111.fits  shape=(800, 800)  dtype=float32


In [21]:
# Verify the output FITS file
with fits.open(fits_file_halo) as hdul:
    hdul.info()
    print()
    print(repr(hdul[0].header))

Filename: grid_halo_TNG100-1_99_111.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU      11   (800, 800)   float32   

SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -32 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  800                                                  
NAXIS2  =                  800                                                  
SIM     = 'TNG100-1'           / IllustrisTNG simulation                        
SNAP    =                   99 / Snapshot number                                
HALO_ID =                  111 / Subhalo/halo ID                                
TYPE    = 'halo    '           / Object type                                    
FILL_VAL=                 99.0 / Sentinel value for empty pixels                
BUNIT   = 'log SB  '